[project]
name = "containment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Quinn Dougherty", email = "quinn.dougherty.forall@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.50.0",
    "jinja2>=3.1.6",
    "mcp>=1.7.1",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
    "typer>=0.15.3",
]

[project.scripts]
contain = "containment:contain"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.8",
]
